### ISSUE TITLE
Enhanced client/server version agreement

### ISSUE THREAD

**Issue by 617a7a** [valeralabs/hardlight#9]
```[tasklist]
### Tasks
- [ ] Evaluate wants/needs for version agreement
- [ ] Decide on the best solution to ensure client/server API version is the same
- [ ] Implement new agreement for runtime client and server
```

#### TLDR

We currently (#7) do a basic check to ensure the client and server use the same major version of HardLight. We want to explore additional methods to ensure the client and server don't encounter issues during a connection because they use different trait versions.

#### Relevant code

https://github.com/valeralabs/hardlight/blob/8a945ed4a5aaa0c501c5609bb13609981a3acd37/src/server.rs#L138-L152

https://github.com/valeralabs/hardlight/blob/8a945ed4a5aaa0c501c5609bb13609981a3acd37/src/client.rs#L123-L129
